- name: Setting up the web server
  hosts: web
  tasks:
          - name: Install Apache
            yum:
                    name: httpd
                    state: present
            tags:
                    - deploy
          - name: Uninstall Apache
            yum:
                    name: httpd
                    state: removed
            tags:
                    - undeploy
          - name: Ensure the service is running
            service:
                    name: httpd
                    state: started
            tags:
                    - deploy
          - name: Modify Apache to listen on 8080
            lineinfile: dest=/etc/httpd/conf/httpd.conf regexp="^Listen 80" line="Listen 8080" state=present
            notify:
                    - restart apache
            tags:
                    - deploy
          - name: Create a blank index file
            file:
                    dest: /var/www/html/index.html
                    state: touch
            tags:
                    - deploy
          - name: Remove the index file
            file:
                    dest: /var/www/html/index.html
                    state: absent
            tags:
                    - undeploy
          - name: Modify default welcome file
            blockinfile: 
                    path: /var/www/html/index.html
                    marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
                    block: |
                            <h1>Hello World print from {{ ansible_hostname }}</h1>
            tags:
                    - deploy
          - name: Open firewall for 8080
            firewalld:
                    port: 8080/tcp
                    permanent: yes
                    state: enabled
            tags:
                    - deploy
          - name: Close firewall port 8080
            firewalld:
                    port: 8080/tcp
                    state: disabled
            tags:
                    - undeploy
          - name: restart firewalld
            service:
                    name: firewalld
                    state: restarted
            tags:
                    - deploy
  handlers:
          - name: restart apache
            service:
                    name: httpd
                    state: restarted


