- name: Setting up the web server
  hosts: web
  tasks:
          - name: Install Apache
            yum:
                    name: httpd
                    state: present
          - name: Modify Apache to listen on 8080
            lineinfile: dest=/etc/httpd/conf/httpd.conf regexp="^Listen 80" line="Listen 8080" state=present
            notify:
                    - restart apache
          - name: Create a blank index file
            file:
                    dest: /tmp/file
                    state: touch
          - name: Modify default welcome file
            blockinfile: 
                    path: /tmp/file
                    marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
                    block: |
                            <h1>Welcome to {{ ansible_hostname }}</h1>
          - name: ensure the service is running
            service:
                    name: httpd
                    state: started
          - name: Open firewall for 8080
            firewalld:
                    port: 8080/tcp
                    permanent: true
                    state: enabled
          - name: restart firewalld
            service:
                    name: firewalld
                    state: restarted


